---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: dev
  namespace: apps
spec:
  interval: 1m0s
  ref:
    branch: main
  secretRef:
    name: gitlab-auth
  url: https://gitlab.com/abohmeed/myweatherapp
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: gitlab
  namespace: apps
spec:
  interval: 1m0s
  secretRef:
    name: gitlab-auth
  type: oci
  url: oci://registry.gitlab.com/abohmeed/myweatherapp
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: dev
  namespace: apps
spec:
  interval: 1m0s
  path: ./
  prune: false
  serviceAccountName: dev
  sourceRef:
    kind: GitRepository
    name: dev
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: gitlab-auth
  namespace: apps
spec:
  encryptedData:
    password: AgAKtdmCICf1y9flV03V5GfuE2TDiYCaUareyjT0mEMCgQpC709vxx18Zz6LAe2QksKklKl7FIv6aqYdmGlC9vY/7iXajypmFmzkiAkYgI+YLHgylMHPHRdcjYA/YmrUyt2+cTwV2HTsEeY0mziMzz1ifGn98FHWgmyrvXFfTkHKjl+LYfg83ZWQUJAXFHTRS08VghSkZMqoYlwXTHtHEpa7WrBbmalNWEMSL5cggXF0NyGPTmdzGQ922GXucFvO+HwNztK7vbur8kHTVUFkA26rg7aB3YyHBYnUf8jii5XVQUlyqfUuVI1nlHQOgzuhR7y4A7IxQ87q/ure4cSzCUpPLm0/Kq6F/JVGVzjNq9uzQk4jZuu/hwi7wWprtqaHZXiLRUIGo8dZyn5AUudWvFViMxZWH7cVqGMK2AZ1Cgjr7kqfY/yjTUy6BJGRGmAaSmX5AUX841UnlyFPKhtTL7F87UmhVe364fzhJDcHbkkMl8T7EsVXe9FqVgklQec36jlVxJUsupFkSQzwBmiR783BYU3zFsPv0UzbZp6LTywlxw8IuMM6uzOIeHlYRBkx6pM4dhlJAlA04vSr0jfFBFPlrRO1AoXNhgWi+G4Zd2NygLMZFATJgYKesnAzOVFPUFEARCkyrUci6YTJs7NkDGJQDqx6GN1ANfPVbq+WcbuiEJNmzGMLEggHQCymgKtEYnHR01ozHeEmq9SjZUvQU5d6k+qeMFrcdXfaWA==
    username: AgCxoE/SnRZ4udT1Lq3o0kqGvS0yQd1/7bDY5u0qbHbGh78hEiviEh0fSFusu4sLstFcU34mixuKvOK+ob8qOobxoYk8PFTiRq92LqFwlbJH1oCohMEe14KkCgjlAaqXVhjmCJo7N7fDLov7TN7h8GdziO2NA2lZko+Kk9/yuqbKWIGavIgQ2qcFxS33hHCnYdfPVb6bhSnZ0+ayKW57ckZEPGaxVVIXYhQc0nkQv5SUppq6k8zNMQsdxlcjfFupMQkYb1gTJ9ygO2MeOV5X7C9dSKDqclzno9T0Xo9pDJUPKf3/a2SjDZcDJU1fKBEBddCwF+wXxHSEcbMvZBz0KIyDfeYYpF1eCPj/eDejBXVbCeyNqX1QKh+h+LgOORt9rHrH0VgnJurQeCohrdM0nwro/vootslxXPEqSeAi5BkAWW+uGaQNkgbtuRpSqWw6AQzFeSp9pNOiIX6KCsioDlOCn6nuriaHXH5AdBzjG22qUbHCRXGk8l7QTXkrUKvj3kVx3FS2bb5p/u2rpxI0pToG4ZS/OSqEzBeAXAEQuJiGuoRHR1cIP/GWwjzBbTorhLL/jOFhRgUBfts0OoGIl9WKs+/3v0S7P/zIPxt10Y6fUdYJezZgc1GaIOmNS/ehcYmQo+iEKg9Rt/STOcqT/IjdPIN1qWjjlkZl17o9IbdaqXvPKP6c00IPgg/O6X9XHq/lQtWqQ5+OI9fzuZgyM4JStp0=
  template:
    metadata:
      creationTimestamp: null
      name: gitlab-auth
      namespace: apps

